name: Webapp deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.19.0
        with:
          channel: stable
          flutter-version: 3.29.2
          
      - name: Get deps
        run: flutter pub get
        
      - name: Build webapp
        run: flutter build web --base-href "/archipelabutt/"

      - name: Upload webapp
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web/
          retention-days: 30

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
